spring:
  application:
    name: document-e2e
  profiles:
    active: local
  cloud:
    openfeign:
      client:
        config:
          default:
            connectTimeout: 500000
            readTimeout: 500000