spring:
  application:
    name: document-app
  profiles:
    active: local
  main:
    allow-bean-definition-overriding: true
  # Exclude DataSourceAutoConfiguration to prevent Spring Boot from configuring a datasource
  autoconfigure:
    exclude:
      - org.springframework.boot.autoconfigure.jdbc.DataSourceAutoConfiguration
      - org.springframework.boot.autoconfigure.orm.jpa.HibernateJpaAutoConfiguration
